name: OKX Tick Cron

on:
  schedule:
    - cron: "*/5 * * * *"    # кожні 10 хв (UTC)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      CRON_URL: ${{ secrets.CRON_URL || vars.CRON_URL }}
      CRON_SECRET: ${{ secrets.CRON_SECRET || vars.CRON_SECRET }}
    steps:
      - name: Sanity check env
        run: |
          [ -n "$CRON_URL" ] && echo "CRON_URL: set" || (echo "CRON_URL missing"; exit 1)
          [ -n "$CRON_SECRET" ] && echo "CRON_SECRET: set" || (echo "CRON_SECRET missing"; exit 1)

      - name: Call /api/cron/tick
        run: |
          set -e
          curl -fsS "$CRON_URL?token=$CRON_SECRET"
          echo "OK"
